version: "~> 1.0"
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: node_js
node_js:
- 8.16.2
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: wdda+ChsX3Z6dVXbiHxQan1bMknQMjTWlY42zdyZykL//VtwXmAZfuySwNt+3o6D/JVzr8zpUFxzWS050TFwU2HTKX0p14WhYdWWpqPuE+is1Hss6W7GtflHNzbZW2CJfi6/PcHqSCtShPQUkFAPl9OVtc56B/bC6jx5c4MvxPUIzrBP+XHttp2kJDOH0HVv3E09ogpYnu6+XDgZuMQQJrQKPy1vy1VblTY7QSzBTTJDthzy7tDdNwFxuMg5GavGGyNQ2XEGWNzkau0pG+z9KW2VrlTl7iXpgGWjjyBDVUOUq2jYx2MHLsxHnmVjHdQzlNsa5HZKjBUKLk17Y2whT1kbt0u4CCO26C/cnsOx8TI6vUkYVh/A6GtLRGO84RqxiV452vJv7jDnfYDjjz2Z974hDyQEbgkBZWJoVFqHYyRNInL9+se6ltbzvHrJdr/pm7bNsX5T84qskksNS/ovK1bftvahQFrIKJnysRHW/3S/BHbsNhT3iCYGt4OimH9OxAYPhT8D7WPeBgyOXxwiKzZijXuq2UZG+qvLTYwjUOQL/+Rr/BAw5JmYAJczZABrcY3vH1eWEpYBJFzh+ws2qosIaipM/tVhn9FpAYAfRPelo/Lz5zBlv+uWNpeKu77J+K610dH7t///KHLhgPAqsVF3PNyIn0u1n59mZt60k2k=
before_script:
- npm install
- npm install -g codecov
script:
- npm run test
- codecov --disable=gcov
